#!/usr/bin/env python3
"""
BreathOS Engine — scan.py
Version: 0.1
Datestamp: 2026-03-27

PURPOSE:
  Probe the current AI landscape for a given topic.
  Output a structured delta file compatible with /map/ format.

USAGE:
  python scan.py --topic "SSM architectures" --cluster architectures
  python scan.py --topic "Llama 4 local inference" --cluster models
  python scan.py --topic "MCP protocol updates" --cluster deployment

OUTPUT:
  Writes a dated delta file to /log/YYYY-MM-DD-delta-[cluster].md

STATUS:
  Scaffold only. Requires API keys and dependencies to run.
  See SETUP section below.
"""

import argparse
import datetime
import os
import sys

# SETUP:
# pip install anthropic
# export ANTHROPIC_API_KEY=your_key_here

SCAN_PROMPT_TEMPLATE = """
You are a research sensor for a personal AI knowledge system called BreathOS.

Your task: scan the current state of knowledge on the topic below and produce a structured delta report.

Topic: {topic}
Cluster: {cluster}

Return your response in this exact structure:

## What's current (as of today)
[3-5 bullet points of the most important current facts]

## What changed recently
[What is meaningfully different from 6-12 months ago? Be specific.]

## What's still open / uncertain
[What remains genuinely unknown or contested?]

## Signal vs noise
[What claims in this space are hype vs. substantiated?]

## Recommended depth files to update
[Which /map/clusters/ files should be reviewed based on this scan?]

## Sources consulted
[List key sources with approximate dates]

Be honest about uncertainty. Say "I don't know" when you don't know.
Datestamp: {date}
"""

def build_delta_entry(topic: str, cluster: str, scan_result: str, date: str) -> str:
    slug = topic.lower().replace(" ", "-")[:40]
    return f"""# Delta: {topic}

**Date:** {date}
**Type:** delta
**Cluster:** {cluster}
**Triggered by:** manual scan via engine/scan.py
**Topic:** {topic}

---

{scan_result}

---

*Generated by BreathOS engine/scan.py v0.1*
*Review and edit before committing to /map/*
"""

def scan(topic: str, cluster: str) -> None:
    date = datetime.date.today().isoformat()

    try:
        import anthropic
        client = anthropic.Anthropic()

        print(f"Scanning: {topic} [{cluster}]...")

        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1500,
            messages=[{
                "role": "user",
                "content": SCAN_PROMPT_TEMPLATE.format(
                    topic=topic,
                    cluster=cluster,
                    date=date
                )
            }]
        )

        result = message.content[0].text
        delta = build_delta_entry(topic, cluster, result, date)

        slug = topic.lower().replace(" ", "-")[:40]
        filename = f"log/{date}-delta-{slug}.md"

        os.makedirs("log", exist_ok=True)
        with open(filename, "w") as f:
            f.write(delta)

        print(f"Delta written to: {filename}")
        print("Review and edit before committing to /map/")

    except ImportError:
        print("ERROR: anthropic package not installed.")
        print("Run: pip install anthropic")
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="BreathOS scan — probe the AI landscape")
    parser.add_argument("--topic", required=True, help="Topic to scan")
    parser.add_argument("--cluster", required=True,
                        choices=["architectures", "models", "intelligence",
                                 "memory", "modalities", "deployment", "hardware", "impact"],
                        help="Which map cluster this relates to")
    args = parser.parse_args()
    scan(args.topic, args.cluster)
